name: Build and publish Nuget

on:
  release:
    types: [published]

env:
  NuGetDirectory: ${{ github.workspace}}/.nuget

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build DexieNET and DexieCloudNET
      run: dotnet build DexieCloudNET/DexieCloudNET.csproj -c Release

    - name: Pack DexieNET
      run: dotnet pack DexieNET/DexieNET.csproj -c Release

    - name: Pack DexieCloudNET
      run: dotnet pack DexieCloudNET/DexieCloudNET.csproj -c Release

    - name: TestSG
      run: dotnet test DexieNETTest/TableGeneratorTest/DexieNETTest.TableGeneratorTest.csproj -c Release

    - name: TestDB
      run: dotnet test DexieNETTest/Tests/DexieNETTest.Tests.csproj -c Release
      
    - name: Publish
      run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json